### ISSUE TITLE
Enter 1 or more item numbers separated by a space -> fails

### ISSUE THREAD

**Issue by fehrmanns** [sprintly/Sprintly-GitHub#36]
Hey. I haven't used the sprintly hook for a while (there was an OS update in between also). As I started to use it again I get an error when I'm trying to commit stuff. Just typing 'sprintly' works fine and I get the list of issues. But when I try to insert a number it fails.
Anyone an idea? Unfortunately I have no knowledge about Python and the task which are going on in the background. So I re-install sprintly and the hook but nothing different happens.

git commit -a -m 'test commit'
Backlog
Product: track-n-trace.it (https://sprint.ly/product/20##2/)
 #63: Check process through registration
 #15: As a bootstrap framework, I want a unify theme so that I will look better.

In Progress
Product: track-n-trace.it (https://sprint.ly/product/20##2/)
 #68: Setup Test
 #44: As an admin I like to add an IMEI to an User Account
 #43: As a user, I want to see the position of my vehicle after login so that I can be sure it's still there.
#0 - Proceed without Sprint.ly item number.

Enter 1 or more item numbers separated by a space: 68
`Traceback (most recent call last):`
`File ".git/hooks/commit-msg", line 143, in <module>
    sys.exit(subprocess.call([original_commit_msg, sys.argv[1]]))`
`File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()`
`File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)`
`File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception`
`OSError: [Errno 8] Exec format error`

**Comment by nicholasserra** [comment]
Hm, i'll check this out. Can you give me a full list of commands you entered to see this error?

**Comment by fehrmanns** [comment]
@nicholasserra I updated the complete procedure in my first post. For me it was the 'normal' flow.

**Comment by nicholasserra** [comment]
Thanks. This looks like an issue running the commit hook subprocess. You said you reinstalled it? I'm wondering if you may need to completely remove the tool and reinstall. 

There may be traces of the commit-hook file around. It may be in your git directory at project/.git/hooks/commit-msg and in your home directory at  ~/.sprintly/commit-msg.

Would be interested to see if removing these, along with the sprintly utility and then reinstalling would work.

Looks like `sprintly --uninstall-hook` will try to uninstall the hook for you, but might want to check afterwards.
